###
GET http://localhost:13000

###
POST http://localhost:13000/setup
###
POST http://localhost:13000/api/auth/register
Content-Type: application/json

{
    "email": "email22@cool.com",
    "password": "pass123"
}

###
POST http://localhost:13000/api/auth/login
Content-Type: application/json

{
    "email": "email@cool.com",
    "password": "pass123"
}
###

POST http://localhost:13000/api/auth/refresh
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJpZCI6MSwiZW1haWwiOiJlbWFpbEBjb29sLmNvbSJ9LCJpYXQiOjE3NjI3MTk4MzQsImV4cCI6MTc2MjgwNjIzNH0.VVBzd_LScgavURXW1QvrqbybkFu6Mp3Md0JOyoYM2AE"
}

### user
GET http://localhost:13000/api/user/search?limit=2&search=
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJpZCI6MSwiZW1haWwiOiJlbWFpbEBjb29sLmNvbSJ9LCJpYXQiOjE3NjMwNzIzNzAsImV4cCI6MTc2MzA3MjY3MH0.GkndtUzA3dpmwK1MR_IOGeF4LKB7OlLIyOW9q8UvYQk

### posts
GET http://localhost:13000/api/posts/byUserId?userId=1&limit=2&offset=0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJpZCI6MSwiZW1haWwiOiJlbWFpbEBjb29sLmNvbSJ9LCJpYXQiOjE3NjMwMzQ2NDAsImV4cCI6MTc2MzAzNDk0MH0.Ui2j70jIFDPTcCKdYDPV0sDj_utwboIHfVNoYIi3P_c
###
GET http://localhost:13000/api/posts?userId=1&limit=5&offset=0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJpZCI6MSwiZW1haWwiOiJlbWFpbEBjb29sLmNvbSJ9LCJpYXQiOjE3NjMwNTY4NjIsImV4cCI6MTc2MzA1NzE2Mn0.n5TOce-juYZ25KX2oDHvfC9Tufvjr8UYEOCM7pqTWZQ
###
POST http://localhost:13000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJpZCI6MSwiZW1haWwiOiJlbWFpbEBjb29sLmNvbSJ9LCJpYXQiOjE3NjI4MDUyNjEsImV4cCI6MTc2MjgwNTU2MX0.fPy3BOSyBWZFQcF4KYKuuDjoLQU9fbMkxIWN0rumjgA
Content-Type: application/json
{
    "content": "Super cool post content2",
    "images": ["image1", "image2"]
}
###
DELETE http://localhost:13000/api/posts?postId=31
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJpZCI6MSwiZW1haWwiOiJlbWFpbEBjb29sLmNvbSJ9LCJpYXQiOjE3NjMwMjU0NTQsImV4cCI6MTc2MzAyNTc1NH0.nyYS6O1SGahV-ZEYTi4Fugm39hC5_1jws_E34A2S0hE
###
PUT http://localhost:13000/api/posts?postId=35
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJpZCI6MSwiZW1haWwiOiJlbWFpbEBjb29sLmNvbSJ9LCJpYXQiOjE3NjMwMzQ2NDAsImV4cCI6MTc2MzAzNDk0MH0.Ui2j70jIFDPTcCKdYDPV0sDj_utwboIHfVNoYIi3P_c
Content-Type: application/json
{
    "content": "Put content2",
    "images": ["file-1763033518322-991542691.jpg"]
}
### user
POST http://localhost:13000/api/user/edit
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJpZCI6MSwiZW1haWwiOiJlbWFpbEBjb29sLmNvbSJ9LCJpYXQiOjE3NjI3MjY3MDYsImV4cCI6MTc2MjcyNzAwNn0.6PT44piO1sr4cBuhO-MdDESzT7shuXAXz01kIHdeP48
Content-Type: application/json
{
    "username": "new username",
    "profileImage": "file-1762726731539-146263654.jpg"
}
###

POST http://localhost:13000/api/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJpZCI6MSwiZW1haWwiOiJlbWFpbCJ9LCJpYXQiOjE3NjI0NjAzNDksImV4cCI6MTc2MjU0Njc0OX0.Bhh3PItqB1K0nFomYzvmtkrcgDHnvAF7-jTnyH2nSEo"
}

###
GET http://localhost:13000/api/profile?userId=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJpZCI6MSwiZW1haWwiOiJlbWFpbEBjb29sLmNvbSJ9LCJpYXQiOjE3NjI3MDY3OTMsImV4cCI6MTc2MjcwNzA5M30.iLZA006kkaKguRgxhXe_Z1nW14cQ-zXBQi5-9BNHfqs
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJpZCI6MiwiZW1haWwiOiJlbWFpbDIifSwiaWF0IjoxNzYyNDU2MzQ4LCJleHAiOjE3NjI0NTY2NDh9.L5dlDJKZ-0ROSYeaJ3TIjSOSNbG6Q2CClcburNbpN68

###
POST http://localhost:13000/api/profile/
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJpZCI6MSwiZW1haWwiOiJlbWFpbCJ9LCJpYXQiOjE3NjI0NTYyNDgsImV4cCI6MTc2MjQ1NjU0OH0.YULr6BOZt7u9Q4PJ-H6d17H_YsIQubG4jR8ahN-hv_k
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJpZCI6MSwiZW1haWwiOiJlbWFpbEBjb29sLmNvbSJ9LCJpYXQiOjE3NjI3MDE4MDIsImV4cCI6MTc2MjcwMjEwMn0.GUS5OewrXNWOUdHND-vZ_nsP6OT6oYnCrxVUlMNQfu8
Content-Type: application/json

{
    "description": "Looooooong description"
}